<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-semibold text-gray-800">Bank Transfer Verification</h2><p class="text-sm text-gray-500">Finance review queue for uploaded payment slips.</p></div><a href="{{ route('admin.finance.index') }}" class="text-sm font-semibold text-green-700 underline">Finance overview</a></div></x-slot>
    <div class="bg-[#F4FFF7] py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="mb-5 rounded-2xl bg-white p-4 text-sm font-medium text-green-700 shadow-sm">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
        <form class="mb-5 flex flex-wrap gap-2" method="GET">
            @foreach(['' => 'All', 'pending_verification' => 'Awaiting review', 'pending_upload' => 'Pending upload', 'verified' => 'Verified', 'rejected' => 'Rejected'] as $value => $label)
                <button name="status" value="{{ $value }}" class="rounded-full px-4 py-2 text-sm font-bold {{ $status === $value ? 'bg-green-600 text-white' : 'bg-white text-gray-700 shadow-sm' }}">{{ $label }}</button>
            @endforeach
        </form>
        <div class="overflow-hidden rounded-3xl bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-100 text-left text-sm"><thead class="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-5 py-4">Order / customer</th><th class="px-5 py-4">Amount / reference</th><th class="px-5 py-4">Payment slip</th><th class="px-5 py-4">Uploaded</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Review</th></tr></thead><tbody class="divide-y divide-gray-100">
        @forelse($payments as $transfer)
            @php($latestSlip = $transfer->slips->sortByDesc('uploaded_at')->first())
            <tr class="align-top"><td class="px-5 py-4"><p class="font-bold text-gray-900">{{ $transfer->payment->order->order_number }}</p><p class="mt-1 text-gray-600">{{ $transfer->payment->order->customer?->user?->name ?? 'Customer' }}</p></td><td class="px-5 py-4"><p class="font-semibold">LKR {{ number_format($transfer->expected_amount, 2) }}</p><p class="mt-1 text-xs text-gray-500">{{ $transfer->reference_number }}</p></td><td class="px-5 py-4">@if($latestSlip)<a class="font-semibold text-green-700 underline" href="{{ route('admin.bank-transfer-slips.download', $latestSlip) }}">{{ $latestSlip->original_name }}</a>@else<span class="text-gray-400">No slip</span>@endif</td><td class="px-5 py-4 text-gray-600">{{ $transfer->submitted_at?->format('d M Y, h:i A') ?? '—' }}</td><td class="px-5 py-4"><span class="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold uppercase text-orange-700">{{ str_replace('_', ' ', $transfer->status) }}</span>@if($transfer->last_rejection_reason)<p class="mt-2 max-w-xs text-xs text-red-600">{{ $transfer->last_rejection_reason }}</p>@endif</td><td class="px-5 py-4">@if(in_array($transfer->status, ['slip_uploaded','pending_verification']))<form method="POST" action="{{ route('admin.bank-transfer-verifications.approve', $transfer) }}" class="mb-2">@csrf @method('PATCH')<button class="rounded-full bg-green-600 px-3 py-2 text-xs font-bold text-white">Approve</button></form><form method="POST" action="{{ route('admin.bank-transfer-verifications.reject', $transfer) }}" class="space-y-2">@csrf @method('PATCH')<input required name="reason" placeholder="Rejection reason" class="w-44 rounded-lg border-gray-200 text-xs"><button class="rounded-full border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Reject & request slip</button></form><form method="POST" action="{{ route('admin.bank-transfer-verifications.request-new-slip', $transfer) }}" class="mt-2 space-y-2">@csrf @method('PATCH')<input required name="reason" placeholder="Request details" class="w-44 rounded-lg border-gray-200 text-xs"><button class="text-xs font-semibold text-orange-700 underline">Request new slip</button></form>@else<span class="text-xs text-gray-400">No action required</span>@endif</td></tr>
        @empty
            <tr><td colspan="6" class="px-5 py-12 text-center text-gray-500">No bank-transfer payments match this filter.</td></tr>
        @endforelse
        </tbody></table></div></div><div class="mt-5">{{ $payments->links() }}</div>
    </div></div>
</x-app-layout>
