<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold">{{ __('Newsletter Management') }}</h2></x-slot>
    <div class="py-12"><div class="mx-auto max-w-7xl sm:px-6 lg:px-8"><div class="bg-white p-6 shadow-sm sm:rounded-lg">
        @if (session('status'))<div class="mb-4 text-sm font-medium text-green-700">{{ session('status') }}</div>@endif
        <form method="GET" class="mb-6 grid gap-3 sm:grid-cols-3"><x-text-input name="search" placeholder="Search email" :value="request('search')" /><select name="status" class="border-gray-300 rounded-md shadow-sm"><option value="">{{ __('All statuses') }}</option>@foreach (['active','inactive','unsubscribed'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><x-primary-button>{{ __('Filter') }}</x-primary-button></form>
        <table class="min-w-full divide-y divide-gray-200 text-sm"><tbody class="divide-y divide-gray-100">@forelse ($subscriptions as $subscription)<tr><td class="py-3 font-semibold">{{ $subscription->email }}</td><td class="py-3">{{ ucfirst($subscription->status) }}</td><td class="py-3"><x-local-time :date="$subscription->subscribed_at" format="date" /></td><td class="py-3 text-right"><form method="POST" action="{{ route('admin.newsletter.update', $subscription) }}" class="inline-flex gap-2">@csrf @method('PATCH')<select name="status" class="text-sm border-gray-300 rounded-md">@foreach (['active','inactive','unsubscribed'] as $status)<option value="{{ $status }}" @selected($subscription->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="text-indigo-700 underline">{{ __('Save') }}</button></form></td></tr>@empty<tr><td class="py-6 text-center text-gray-500">{{ __('No subscriptions found.') }}</td></tr>@endforelse</tbody></table>
        <div class="mt-6">{{ $subscriptions->links() }}</div>
    </div></div></div>
</x-app-layout>
