<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-gray-800">{{ __('Delivery Fee Rules') }}</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded bg-green-50 p-4 text-green-700">{{ session('status') }}</div>@endif
        <form method="POST" action="{{ route('super-admin.delivery.rules.store') }}" class="grid gap-3 rounded-lg bg-white p-5 shadow sm:grid-cols-4">@csrf
            <select name="scope" class="rounded border-gray-300"><option value="zone">Zone</option><option value="district">District</option><option value="province">Province</option><option value="default">Default</option></select>
            <select name="zone_id" class="rounded border-gray-300"><option value="">No zone</option>@foreach($zones as $zone)<option value="{{ $zone->id }}">{{ $zone->name }}</option>@endforeach</select>
            <x-text-input name="district" placeholder="District" /><x-text-input name="province" placeholder="Province" />
            <x-text-input name="base_fee" type="number" min="0" step="0.01" placeholder="Base fee" required /><x-text-input name="per_km_fee" type="number" min="0" step="0.01" placeholder="Per KM fee" required /><x-text-input name="minimum_order" type="number" min="0" step="0.01" placeholder="Minimum order" required /><x-text-input name="free_delivery_threshold" type="number" min="0" step="0.01" placeholder="Free delivery threshold" />
            <x-text-input name="maximum_distance_km" type="number" min="0" step="0.01" placeholder="Maximum distance KM" /><x-text-input name="estimated_delivery_minutes" type="number" min="1" placeholder="ETA minutes" /><x-text-input name="priority" type="number" min="0" value="100" required /><select name="status" class="rounded border-gray-300"><option value="active">Active</option><option value="inactive">Inactive</option></select>
            <x-text-input name="starts_on" type="date" /><x-text-input name="ends_on" type="date" /><x-primary-button>{{ __('Add rule') }}</x-primary-button>
        </form>
        <div class="overflow-x-auto rounded-lg bg-white shadow"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left"><tr><th class="p-3">Scope</th><th>Target</th><th>Formula</th><th>Free threshold</th><th>ETA</th><th>Priority</th><th>Status</th></tr></thead><tbody class="divide-y">@forelse($rules as $rule)<tr><td class="p-3 font-semibold">{{ ucfirst($rule->scope) }}</td><td>{{ $rule->zone?->name ?? $rule->district ?? $rule->province ?? 'All locations' }}</td><td>Rs. {{ number_format($rule->base_fee,2) }} + Rs. {{ number_format($rule->per_km_fee,2) }}/km</td><td>{{ $rule->free_delivery_threshold ? 'Rs. '.number_format($rule->free_delivery_threshold,2) : '—' }}</td><td>{{ $rule->estimated_delivery_minutes ? $rule->estimated_delivery_minutes.' min' : '—' }}</td><td>{{ $rule->priority }}</td><td>{{ ucfirst($rule->status) }}</td></tr>@empty<tr><td colspan="7" class="p-6 text-center text-gray-500">No prioritized delivery rules configured.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $rules->links() }}</div></div>
    </div></div>
</x-app-layout>
